language: node_js
node_js:
    - "stable"
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
before_script:
  - "npm i"
script:
  - "npm run predeploy"
after_success:
  - "npm run deploy"
