language: node_js
node_js:
    - "stable"
cache:
  directories:
    - node_modules
branches:
  only:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
before_script:
  - "npm i"
  - "npm i -g gatsby"
script:
  - "gatsby build --prefix-paths"
after_success:
  - "npm run deploy"
